apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-i0n6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-i0n6@sha256:93c07a7fab593a605c60f9ee9958584cf7c2e34e748b4577d6defe99534b0df1
        name: my-nodejs
        resources: {}
status: {}
